# Generated by devtools/yamaker from nixpkgs 24.05.

SUBSCRIBER(g:cpp-contrib)

VERSION(1.17.0)

ORIGINAL_SOURCE(https://github.com/google/googletest/archive/v1.17.0.tar.gz)

RECURSE(
    googlemock
    googletest
)
